// <auto-generated />
namespace BugTrackerWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Email_Migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Email_Migration));
        
        string IMigrationMetadata.Id
        {
            get { return "202105170002536_Email_Migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
